---
- name: "Waiting until 5min for server to come back"
  local_action: wait_for port=22 host="{{ ansible_host }}" search_regex=OpenSSH delay=30 timeout=300
  remote_user: dev
  become: false

- include: 1_install_libvirt_guestfish.yml

- include: 2_configure_libvirt.yml 
