---

- name: "Applying: iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE"
  command: "{{ item }}"
  with_items:
    - 'iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE'
    - 'iptables-save'
